name: Release Obsidian plugin

on:
  release:
    types:
      - created

env:
  PLUGIN_NAME: obsidian-share-to-gitlab-snippets-plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build
        id: build
        run: |
          npm install
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls

      - name: Upload zip archive
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: ${{ env.PLUGIN_NAME }}-$GITHUB_REF_NAME.zip
          path: ${{ env.PLUGIN_NAME }}.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/zip

      - name: Upload main.js
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: main.js
          path: main.js
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: text/javascript

      - name: Upload manifest.json
        uses: Shopify/upload-to-release@v1.0.1
        with:
          name: manifest.json
          path: manifest.json
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          content-type: application/json